eog ~/XMOS/autoump/BallFilterTest/images/09/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/10/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/11/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/12/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/13/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/14/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/15/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/16/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/17/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/18/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/19/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/20/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/21/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/22/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/23/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/42/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/43/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/44/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/45/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/46/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/47/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/48/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/49/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/50/computed/0.png

