eog ~/XMOS/autoump/BallFilterTest/images/25/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/28/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/30/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/32/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/33/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/36/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/37/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/38/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/39/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/40/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/41/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/51/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/52/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/54/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/56/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/57/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/58/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/60/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/61/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/62/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/63/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/64/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/66/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/68/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/69/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/70/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/71/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/72/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/74/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/75/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/76/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/77/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/78/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/79/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/80/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/82/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/83/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/85/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/86/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/87/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/88/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/89/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/91/computed/0.png
eog ~/XMOS/autoump/BallFilterTest/images/92/computed/0.png

